//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::resource_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::resouce_resouce_type::Relation::ResourceType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::resouce_resouce_type::Relation::Resource.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
